In [17]:
import numpy as np

In [18]:
A = [[1,2,3],[4,5,6],[7,8,9]]
B = [[9,8,7],[6,5,4],[3,2,1]]
C = [[1,2],[3,4],[5,6]]

In [19]:
def determinante_matriz(A):
    return np.linalg.det(A)

In [20]:
def inversa_matriz(A):
    return np.linalg.inv(A)

In [21]:
print(determinante_matriz(A))

0.0


In [22]:
print(determinante_matriz(B))

0.0


In [23]:
D = [[2,2,-5], [3,-3,9], [3,4,3]]

In [24]:
print(inversa_matriz(D))

[[ 0.28301887  0.16352201 -0.01886792]
 [-0.11320755 -0.13207547  0.20754717]
 [-0.13207547  0.01257862  0.0754717 ]]


In [25]:
print(determinante_matriz(D))

-159.0


In [26]:
import numpy as np

A = np.array([[2, 3, -1], [4, 1, 2], [-2, 5, 3]])

B = np.array([1, 5, 0])

In [27]:
soluciones = np.linalg.solve(A, B)

print(soluciones[0], soluciones[1], soluciones[2])

0.9166666666666666 -0.04761904761904769 0.6904761904761906


In [28]:
import numpy as np

In [29]:
def transform_vector(vector, transformation_matrix):
    return np.dot(transformation_matrix, vector)

In [30]:
vector_r2=np.array([1, 2])
transformation_matrix = np.array([[1, 0], [0, 1], [1, 1]])

In [31]:
transformed_vector_r3 = transform_vector(vector_r2, transformation_matrix)

In [32]:
print(vector_r2)
print(transformation_matrix)
print(transformed_vector_r3)

[1 2]
[[1 0]
 [0 1]
 [1 1]]
[1 2 3]


In [33]:
import numpy as np

In [34]:
def transform_vector(vector, transformation_matrix):
    return np.dot(transformation_matrix, vector)

In [35]:
vector_r2 = np.array([1, 2])
transformation_matrix = np.array([[1, 0], [0, 1], [1, 1]])

In [ ]:
transformed_vector_r3 = transform_vector(vector_r2, transformation_matrix)

In [ ]:
print(vector_r2)
print(transformation_matrix)
print(transformed_vector_r3)